format_code_in_doc_comments  = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "module"
reorder_impl_items = true
struct_field_align_threshold = 25
use_field_init_shorthand = true
